def afl_team_data
  [
    {
      id: 1,
      name: 'Adelaide',
      code: 'ADL',
      nickname: 'Crows',
      current: true,
      afltables_url: 'adelaide',
    },
    {
      id: 2,
      name: 'Brisbane',
      code: 'BRI',
      nickname: 'Lions',
      current: true,
      afltables_url: 'brisbanel',
    },
    {
      id: 3,
      name: 'Carlton',
      code: 'CAR',
      nickname: 'Blues',
      current: true,
      afltables_url: 'carlton',
    },
    {
      id: 4,
      name: 'Collingwood',
      code: 'COL',
      nickname: 'Pies',
      current: true,
      afltables_url: 'collingwood',
    },
    {
      id: 5,
      name: 'Essendon',
      code: 'ESS',
      nickname: 'Bombers',
      current: true,
      afltables_url: 'essendon',
    },
    {
      id: 6,
      name: 'Fitzroy',
      code: 'FTZ',
      nickname: 'Lions',
      current: false,
      afltables_url: 'fitzroy',
    },
    {
      id: 7,
      name: 'Fremantle',
      code: 'FRE',
      nickname: 'Dockers',
      current: true,
      afltables_url: 'fremantle',
    },
    {
      id: 8,
      name: 'Geelong',
      code: 'GEE',
      nickname: 'Cats',
      current: true,
      afltables_url: 'geelong',
    },
    {
      id: 9,
      name: 'Gold Coast',
      code: 'GCS',
      nickname: 'Suns',
      current: true,
      afltables_url: 'goldcoast',
    },
    {
      id: 10,
      name: 'Greater Western Sydney',
      code: 'GWS',
      nickname: 'Giants',
      current: true,
      afltables_url: 'gws',
    },
    {
      id: 11,
      name: 'Hawthorn',
      code: 'HAW',
      nickname: 'Hawks',
      current: true,
      afltables_url: 'hawthorn',
    },
    {
      id: 12,
      name: 'Melbourne',
      code: 'MEL',
      nickname: 'Demons',
      current: true,
      afltables_url: 'melbourne',
    },
    {
      id: 13,
      name: 'North Melbourne',
      code: 'NTH',
      nickname: 'Kangaroos',
      current: true,
      afltables_url: 'kangaroos',
    },
    {
      id: 14,
      name: 'Port Adelaide',
      code: 'POR',
      nickname: 'Power',
      current: true,
      afltables_url: 'padelaide',
    },
    {
      id: 15,
      name: 'Richmond',
      code: 'RIC',
      nickname: 'Tigers',
      current: true,
      afltables_url: 'richmond',
    },
    {
      id: 16,
      name: 'St Kilda',
      code: 'STK',
      nickname: 'Saints',
      current: true,
      afltables_url: 'stkilda',
    },
    {
      id: 17,
      name: 'South Melbourne',
      code: 'STH',
      nickname: 'Swans',
      current: false,
      afltables_url: 'swans'
    },
    {
      id: 18,
      name: 'Sydney',
      code: 'SYD',
      nickname: 'Swans',
      current: true,
      afltables_url: 'swans'
    },
    {
      id: 19,
      name: 'West Coast',
      code: 'POR',
      nickname: 'Eagles',
      current: true,
      afltables_url: 'westcoast',
    },
    {
      id: 20,
      name: 'Western Bulldogs',
      code: 'WBD',
      nickname: 'Dogs',
      current: true,
      afltables_url: 'bullldogs',
    },
    {
      id: 21,
      name: 'University',
      code: 'UNI',
      nickname: '',
      current: false,
      afltables_url: 'bullldogs',
    },
  ]
end
